//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawInterviewExercise.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string ImageGuid { get; set; }
        public byte[] Image { get; set; }
        public string ImageFile { get; set; }
        public string VideoUrl { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public string Memo { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
